// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irkptbzumclzynxhdigx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlya3B0Ynp1bWNsenlueGhkaWd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MjMwMzQsImV4cCI6MjA3MTM5OTAzNH0.soKgOUO4I-WVk55RfImvuU7XRjTDLSEKOGdezXlpUN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});